apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookalbum
  labels:
    app: bookalbum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookalbum
  template:
    metadata:
      labels:
        app: bookalbum
    spec:
      containers:
      - name: bookalbum
        image: neehar2601/bookalbum:v1
        ports:
        - containerPort: 80
